In [7]:
import numpy as np
from scipy import ndimage

In [8]:
I = np.array([[1,2,0,0],
              [3,4,0,5],
              [0,0,0,6],
              [7,8,9,10]])
print("I=\n{}\n\n".format(I))

I=
[[ 1  2  0  0]
 [ 3  4  0  5]
 [ 0  0  0  6]
 [ 7  8  9 10]]




In [9]:
f = np.array([[1,0,0],
              [0,0,0],
              [0,0,0]])
print("f=\n{}\n\n".format(f))

f=
[[1 0 0]
 [0 0 0]
 [0 0 0]]




In [10]:
f_conv_I = ndimage.convolve(I, f, mode='constant', cval = 0.0)
print("f_conv_I=\n{}\n\n".format(f_conv_I))

f_conv_I=
[[ 4  0  5  0]
 [ 0  0  6  0]
 [ 8  9 10  0]
 [ 0  0  0  0]]




In [11]:
f_filt_I = ndimage.correlate(I, f, mode = 'constant', cval = 0.0)
print("f_filt_I=\n{}\n\n".format(f_filt_I))

f_filt_I=
[[0 0 0 0]
 [0 1 2 0]
 [0 3 4 0]
 [0 0 0 0]]




In [12]:
###################################################
###              Implementation                 ###
###################################################

In [13]:
def pad_img(img):
    return np.pad(img, pad_width = 1, mode = 'constant', constant_values= 0)

In [34]:
def conv(img, kernel):
    kernel = np.fliplr(kernel)
    flipped_kernel = np.flipud(kernel)
    padded_img = pad_img(img)
    
    new_matrix = np.zeros(img.shape)
    for a in range(1, padded_img.shape[1] - 1):
        for b in range(1, padded_img.shape[1] - 1):
            sum = 0
            k_i = 0
            for i in range(a - 1, a+2):
                k_j = 0
                for j in range( b - 1, b + 2):
                    print("i = {}, j = {}".format(i,j))
                    sum += padded_img[i,j] * flipped_kernel[k_i,k_j]
                    k_j += 1
                k_i +=1
            new_matrix[a - 1,b - 1] = sum
    print(new_matrix)
conv(I, f)

i = 0, j = 0
i = 0, j = 1
i = 0, j = 2
i = 1, j = 0
i = 1, j = 1
i = 1, j = 2
i = 2, j = 0
i = 2, j = 1
i = 2, j = 2
i = 0, j = 1
i = 0, j = 2
i = 0, j = 3
i = 1, j = 1
i = 1, j = 2
i = 1, j = 3
i = 2, j = 1
i = 2, j = 2
i = 2, j = 3
i = 0, j = 2
i = 0, j = 3
i = 0, j = 4
i = 1, j = 2
i = 1, j = 3
i = 1, j = 4
i = 2, j = 2
i = 2, j = 3
i = 2, j = 4
i = 0, j = 3
i = 0, j = 4
i = 0, j = 5
i = 1, j = 3
i = 1, j = 4
i = 1, j = 5
i = 2, j = 3
i = 2, j = 4
i = 2, j = 5
i = 1, j = 0
i = 1, j = 1
i = 1, j = 2
i = 2, j = 0
i = 2, j = 1
i = 2, j = 2
i = 3, j = 0
i = 3, j = 1
i = 3, j = 2
i = 1, j = 1
i = 1, j = 2
i = 1, j = 3
i = 2, j = 1
i = 2, j = 2
i = 2, j = 3
i = 3, j = 1
i = 3, j = 2
i = 3, j = 3
i = 1, j = 2
i = 1, j = 3
i = 1, j = 4
i = 2, j = 2
i = 2, j = 3
i = 2, j = 4
i = 3, j = 2
i = 3, j = 3
i = 3, j = 4
i = 1, j = 3
i = 1, j = 4
i = 1, j = 5
i = 2, j = 3
i = 2, j = 4
i = 2, j = 5
i = 3, j = 3
i = 3, j = 4
i = 3, j = 5
i = 2, j = 0
i = 2, j = 1
i = 2, j = 2
i = 3, j = 0
i = 3, j = 1

In [37]:
def correlation(img, kernel):
    padded_img = pad_img(img)
    
    new_matrix = np.zeros(img.shape)
    for a in range(1, padded_img.shape[1] - 1):
        for b in range(1, padded_img.shape[1] - 1):
            sum = 0
            k_i = 0
            for i in range(a - 1, a+2):
                k_j = 0
                for j in range( b - 1, b + 2):
                    print("i = {}, j = {}".format(i,j))
                    sum += padded_img[i,j] * kernel[k_i,k_j]
                    k_j += 1
                k_i +=1
            new_matrix[a - 1,b - 1] = sum
    print(new_matrix)
correlation(I, f)

i = 0, j = 0
i = 0, j = 1
i = 0, j = 2
i = 1, j = 0
i = 1, j = 1
i = 1, j = 2
i = 2, j = 0
i = 2, j = 1
i = 2, j = 2
i = 0, j = 1
i = 0, j = 2
i = 0, j = 3
i = 1, j = 1
i = 1, j = 2
i = 1, j = 3
i = 2, j = 1
i = 2, j = 2
i = 2, j = 3
i = 0, j = 2
i = 0, j = 3
i = 0, j = 4
i = 1, j = 2
i = 1, j = 3
i = 1, j = 4
i = 2, j = 2
i = 2, j = 3
i = 2, j = 4
i = 0, j = 3
i = 0, j = 4
i = 0, j = 5
i = 1, j = 3
i = 1, j = 4
i = 1, j = 5
i = 2, j = 3
i = 2, j = 4
i = 2, j = 5
i = 1, j = 0
i = 1, j = 1
i = 1, j = 2
i = 2, j = 0
i = 2, j = 1
i = 2, j = 2
i = 3, j = 0
i = 3, j = 1
i = 3, j = 2
i = 1, j = 1
i = 1, j = 2
i = 1, j = 3
i = 2, j = 1
i = 2, j = 2
i = 2, j = 3
i = 3, j = 1
i = 3, j = 2
i = 3, j = 3
i = 1, j = 2
i = 1, j = 3
i = 1, j = 4
i = 2, j = 2
i = 2, j = 3
i = 2, j = 4
i = 3, j = 2
i = 3, j = 3
i = 3, j = 4
i = 1, j = 3
i = 1, j = 4
i = 1, j = 5
i = 2, j = 3
i = 2, j = 4
i = 2, j = 5
i = 3, j = 3
i = 3, j = 4
i = 3, j = 5
i = 2, j = 0
i = 2, j = 1
i = 2, j = 2
i = 3, j = 0
i = 3, j = 1